# Generated by Django 5.0.4 on 2024-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_tag_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='media/blog_images/'),
        ),
    ]
