# Generated by Django 5.0.4 on 2024-04-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/default_blog.jpg', null=True, upload_to='blog_images/'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
